### PR TITLE
Update Data

### PR DESCRIPTION
**Pull request by maennchen**

### CODE REVIEW

**Comment by maennchen** [comment]
Ping

**Comment by maennchen** [comment]
Ping

**Comment by normancapule** [comment]
hey @maennchen! looks like I can update my PR from this PR's updated data

**Comment by maennchen** [comment]
@normancapule Sure, I don't think it's going to be merged though :( I opened #3 to see if this is still maintained...

**Comment by normancapule** [comment]
Hey @maennchen. I know it has been a while. I just updated my fork with changes from your PR.

**Comment by maennchen** [comment]
Closed because of inactivity

**Pull request closed without merging**
